# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\git\OLT_Client\OLTv1_4.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1112, 608))
        MainWindow.setMaximumSize(QtCore.QSize(1112, 16777215))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.comboBox_OLTFactory = QtWidgets.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_OLTFactory.setFont(font)
        self.comboBox_OLTFactory.setObjectName("comboBox_OLTFactory")
        self.comboBox_OLTFactory.addItem("")
        self.comboBox_OLTFactory.setItemText(0, "")
        self.comboBox_OLTFactory.addItem("")
        self.comboBox_OLTFactory.addItem("")
        self.comboBox_OLTFactory.addItem("")
        self.comboBox_OLTFactory.addItem("")
        self.comboBox_OLTFactory.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_OLTFactory)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_IPAddr = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_IPAddr.setFont(font)
        self.lineEdit_IPAddr.setText("")
        self.lineEdit_IPAddr.setObjectName("lineEdit_IPAddr")
        self.horizontalLayout_4.addWidget(self.lineEdit_IPAddr)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.lineEdit_oltUser = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_oltUser.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_oltUser.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_oltUser.setObjectName("lineEdit_oltUser")
        self.horizontalLayout.addWidget(self.lineEdit_oltUser)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_OLTType = QtWidgets.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_OLTType.setFont(font)
        self.comboBox_OLTType.setObjectName("comboBox_OLTType")
        self.comboBox_OLTType.addItem("")
        self.comboBox_OLTType.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_OLTType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.comboBox_loginMethod = QtWidgets.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_loginMethod.setFont(font)
        self.comboBox_loginMethod.setObjectName("comboBox_loginMethod")
        self.comboBox_loginMethod.addItem("")
        self.comboBox_loginMethod.addItem("")
        self.comboBox_loginMethod.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_loginMethod)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lineEdit_oltPasswd = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_oltPasswd.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_oltPasswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_oltPasswd.setObjectName("lineEdit_oltPasswd")
        self.horizontalLayout_9.addWidget(self.lineEdit_oltPasswd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.comboBox_onuType = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_onuType.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_onuType.setFont(font)
        self.comboBox_onuType.setObjectName("comboBox_onuType")
        self.comboBox_onuType.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_onuType)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox_check = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_check.setFont(font)
        self.comboBox_check.setObjectName("comboBox_check")
        self.comboBox_check.addItem("")
        self.comboBox_check.addItem("")
        self.comboBox_check.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_check)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_check = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_check.setFont(font)
        self.label_check.setAlignment(QtCore.Qt.AlignCenter)
        self.label_check.setObjectName("label_check")
        self.horizontalLayout_11.addWidget(self.label_check)
        self.lineEdit_SN = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_SN.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SN.sizePolicy().hasHeightForWidth())
        self.lineEdit_SN.setSizePolicy(sizePolicy)
        self.lineEdit_SN.setMinimumSize(QtCore.QSize(207, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_SN.setFont(font)
        self.lineEdit_SN.setText("")
        self.lineEdit_SN.setObjectName("lineEdit_SN")
        self.horizontalLayout_11.addWidget(self.lineEdit_SN)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.tableWidget_onu = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_onu.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tableWidget_onu.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_onu.setRowCount(1)
        self.tableWidget_onu.setColumnCount(5)
        self.tableWidget_onu.setObjectName("tableWidget_onu")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onu.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tableWidget_onu)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.horizontalLayout_12.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_login = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout_4.addWidget(self.pushButton_login)
        self.pushButton_exit = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_exit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.verticalLayout_4.addWidget(self.pushButton_exit)
        self.pushButton_query = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_query.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_query.setFont(font)
        self.pushButton_query.setObjectName("pushButton_query")
        self.verticalLayout_4.addWidget(self.pushButton_query)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_reg = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_reg.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_reg.setFont(font)
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.gridLayout.addWidget(self.pushButton_reg, 1, 0, 1, 1)
        self.pushButton_addService = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_addService.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_addService.setFont(font)
        self.pushButton_addService.setObjectName("pushButton_addService")
        self.gridLayout.addWidget(self.pushButton_addService, 3, 0, 1, 1)
        self.pushButton_unreg = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_unreg.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_unreg.setFont(font)
        self.pushButton_unreg.setObjectName("pushButton_unreg")
        self.gridLayout.addWidget(self.pushButton_unreg, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 4, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_12.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget_service = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget_service.setMinimumSize(QtCore.QSize(665, 108))
        self.tabWidget_service.setMaximumSize(QtCore.QSize(665, 108))
        self.tabWidget_service.setToolTipDuration(0)
        self.tabWidget_service.setStyleSheet("")
        self.tabWidget_service.setObjectName("tabWidget_service")
        self.widget_Unicast = QtWidgets.QWidget()
        self.widget_Unicast.setObjectName("widget_Unicast")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_Unicast)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_service = QtWidgets.QScrollArea(self.widget_Unicast)
        self.scrollArea_service.setMinimumSize(QtCore.QSize(641, 61))
        self.scrollArea_service.setMaximumSize(QtCore.QSize(641, 61))
        self.scrollArea_service.setWidgetResizable(True)
        self.scrollArea_service.setObjectName("scrollArea_service")
        self.scrollAreaWidgetContents_service = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_service.setGeometry(QtCore.QRect(0, 0, 1011, 42))
        self.scrollAreaWidgetContents_service.setMinimumSize(QtCore.QSize(1011, 0))
        self.scrollAreaWidgetContents_service.setObjectName("scrollAreaWidgetContents_service")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_service)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1011, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_service = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_service.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_service.setObjectName("verticalLayout_service")
        self.horizontalLayout_service_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_service_1.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_service_1.setObjectName("horizontalLayout_service_1")
        self.pushButton_add_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_1.sizePolicy().hasHeightForWidth())
        self.pushButton_add_1.setSizePolicy(sizePolicy)
        self.pushButton_add_1.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_add_1.setFont(font)
        self.pushButton_add_1.setObjectName("pushButton_add_1")
        self.horizontalLayout_service_1.addWidget(self.pushButton_add_1)
        self.label_service_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_service_1.setFont(font)
        self.label_service_1.setObjectName("label_service_1")
        self.horizontalLayout_service_1.addWidget(self.label_service_1)
        self.comboBox_service_1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_service_1.setFont(font)
        self.comboBox_service_1.setObjectName("comboBox_service_1")
        self.comboBox_service_1.addItem("")
        self.comboBox_service_1.addItem("")
        self.comboBox_service_1.addItem("")
        self.comboBox_service_1.addItem("")
        self.horizontalLayout_service_1.addWidget(self.comboBox_service_1)
        self.label_servicevlanmode_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_servicevlanmode_1.setFont(font)
        self.label_servicevlanmode_1.setObjectName("label_servicevlanmode_1")
        self.horizontalLayout_service_1.addWidget(self.label_servicevlanmode_1)
        self.comboBox_servicevlanmode_1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_servicevlanmode_1.setFont(font)
        self.comboBox_servicevlanmode_1.setObjectName("comboBox_servicevlanmode_1")
        self.comboBox_servicevlanmode_1.addItem("")
        self.comboBox_servicevlanmode_1.addItem("")
        self.comboBox_servicevlanmode_1.addItem("")
        self.horizontalLayout_service_1.addWidget(self.comboBox_servicevlanmode_1)
        self.label_svlan_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_svlan_1.setFont(font)
        self.label_svlan_1.setObjectName("label_svlan_1")
        self.horizontalLayout_service_1.addWidget(self.label_svlan_1)
        self.lineEdit_svlan_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_svlan_1.setMaximumSize(QtCore.QSize(52, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_svlan_1.setFont(font)
        self.lineEdit_svlan_1.setObjectName("lineEdit_svlan_1")
        self.horizontalLayout_service_1.addWidget(self.lineEdit_svlan_1)
        self.label_cvlan_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_cvlan_1.setFont(font)
        self.label_cvlan_1.setObjectName("label_cvlan_1")
        self.horizontalLayout_service_1.addWidget(self.label_cvlan_1)
        self.lineEdit_cvlan_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_cvlan_1.setMaximumSize(QtCore.QSize(52, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_cvlan_1.setFont(font)
        self.lineEdit_cvlan_1.setObjectName("lineEdit_cvlan_1")
        self.horizontalLayout_service_1.addWidget(self.lineEdit_cvlan_1)
        self.label_uservlanmode_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_uservlanmode_1.setFont(font)
        self.label_uservlanmode_1.setObjectName("label_uservlanmode_1")
        self.horizontalLayout_service_1.addWidget(self.label_uservlanmode_1)
        self.comboBox_uservlanmode_1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_uservlanmode_1.setFont(font)
        self.comboBox_uservlanmode_1.setObjectName("comboBox_uservlanmode_1")
        self.comboBox_uservlanmode_1.addItem("")
        self.comboBox_uservlanmode_1.addItem("")
        self.comboBox_uservlanmode_1.addItem("")
        self.comboBox_uservlanmode_1.addItem("")
        self.horizontalLayout_service_1.addWidget(self.comboBox_uservlanmode_1)
        self.label_uservlan_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_uservlan_1.setFont(font)
        self.label_uservlan_1.setObjectName("label_uservlan_1")
        self.horizontalLayout_service_1.addWidget(self.label_uservlan_1)
        self.lineEdit_usevlan_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_usevlan_1.setMaximumSize(QtCore.QSize(52, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_usevlan_1.setFont(font)
        self.lineEdit_usevlan_1.setObjectName("lineEdit_usevlan_1")
        self.horizontalLayout_service_1.addWidget(self.lineEdit_usevlan_1)
        self.verticalLayout_service.addLayout(self.horizontalLayout_service_1)
        self.scrollArea_service.setWidget(self.scrollAreaWidgetContents_service)
        self.verticalLayout_6.addWidget(self.scrollArea_service)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget_service.addTab(self.widget_Unicast, "")
        self.widget_Multicast = QtWidgets.QWidget()
        self.widget_Multicast.setObjectName("widget_Multicast")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_Multicast)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_service_2 = QtWidgets.QScrollArea(self.widget_Multicast)
        self.scrollArea_service_2.setMinimumSize(QtCore.QSize(641, 61))
        self.scrollArea_service_2.setMaximumSize(QtCore.QSize(641, 61))
        self.scrollArea_service_2.setWidgetResizable(True)
        self.scrollArea_service_2.setObjectName("scrollArea_service_2")
        self.scrollAreaWidgetContents_service_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_service_2.setGeometry(QtCore.QRect(0, 0, 1011, 42))
        self.scrollAreaWidgetContents_service_2.setMinimumSize(QtCore.QSize(1011, 0))
        self.scrollAreaWidgetContents_service_2.setObjectName("scrollAreaWidgetContents_service_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_service_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1011, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_service_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_service_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_service_2.setObjectName("verticalLayout_service_2")
        self.horizontalLayout_service_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_service_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_service_2.setObjectName("horizontalLayout_service_2")
        self.pushButton_add_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_2.sizePolicy().hasHeightForWidth())
        self.pushButton_add_2.setSizePolicy(sizePolicy)
        self.pushButton_add_2.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_add_2.setFont(font)
        self.pushButton_add_2.setObjectName("pushButton_add_2")
        self.horizontalLayout_service_2.addWidget(self.pushButton_add_2)
        self.label_service_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_service_2.setFont(font)
        self.label_service_2.setObjectName("label_service_2")
        self.horizontalLayout_service_2.addWidget(self.label_service_2)
        self.comboBox_service_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_service_2.setFont(font)
        self.comboBox_service_2.setObjectName("comboBox_service_2")
        self.comboBox_service_2.addItem("")
        self.comboBox_service_2.addItem("")
        self.comboBox_service_2.addItem("")
        self.comboBox_service_2.addItem("")
        self.horizontalLayout_service_2.addWidget(self.comboBox_service_2)
        self.label_servicevlanmode_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_servicevlanmode_2.setFont(font)
        self.label_servicevlanmode_2.setObjectName("label_servicevlanmode_2")
        self.horizontalLayout_service_2.addWidget(self.label_servicevlanmode_2)
        self.comboBox_servicevlanmode_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_servicevlanmode_2.setFont(font)
        self.comboBox_servicevlanmode_2.setObjectName("comboBox_servicevlanmode_2")
        self.comboBox_servicevlanmode_2.addItem("")
        self.comboBox_servicevlanmode_2.addItem("")
        self.comboBox_servicevlanmode_2.addItem("")
        self.horizontalLayout_service_2.addWidget(self.comboBox_servicevlanmode_2)
        self.label_svlan_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_svlan_2.setFont(font)
        self.label_svlan_2.setObjectName("label_svlan_2")
        self.horizontalLayout_service_2.addWidget(self.label_svlan_2)
        self.lineEdit_svlan_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_svlan_2.setMaximumSize(QtCore.QSize(52, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_svlan_2.setFont(font)
        self.lineEdit_svlan_2.setObjectName("lineEdit_svlan_2")
        self.horizontalLayout_service_2.addWidget(self.lineEdit_svlan_2)
        self.label_cvlan_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_cvlan_2.setFont(font)
        self.label_cvlan_2.setObjectName("label_cvlan_2")
        self.horizontalLayout_service_2.addWidget(self.label_cvlan_2)
        self.lineEdit_cvlan_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_cvlan_2.setMaximumSize(QtCore.QSize(52, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_cvlan_2.setFont(font)
        self.lineEdit_cvlan_2.setObjectName("lineEdit_cvlan_2")
        self.horizontalLayout_service_2.addWidget(self.lineEdit_cvlan_2)
        self.label_uservlanmode_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_uservlanmode_2.setFont(font)
        self.label_uservlanmode_2.setObjectName("label_uservlanmode_2")
        self.horizontalLayout_service_2.addWidget(self.label_uservlanmode_2)
        self.comboBox_uservlanmode_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_uservlanmode_2.setFont(font)
        self.comboBox_uservlanmode_2.setObjectName("comboBox_uservlanmode_2")
        self.comboBox_uservlanmode_2.addItem("")
        self.comboBox_uservlanmode_2.addItem("")
        self.comboBox_uservlanmode_2.addItem("")
        self.comboBox_uservlanmode_2.addItem("")
        self.horizontalLayout_service_2.addWidget(self.comboBox_uservlanmode_2)
        self.label_uservlan_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_uservlan_2.setFont(font)
        self.label_uservlan_2.setObjectName("label_uservlan_2")
        self.horizontalLayout_service_2.addWidget(self.label_uservlan_2)
        self.lineEdit_usevlan_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_usevlan_2.setMaximumSize(QtCore.QSize(52, 27))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_usevlan_2.setFont(font)
        self.lineEdit_usevlan_2.setObjectName("lineEdit_usevlan_2")
        self.horizontalLayout_service_2.addWidget(self.lineEdit_usevlan_2)
        self.verticalLayout_service_2.addLayout(self.horizontalLayout_service_2)
        self.scrollArea_service_2.setWidget(self.scrollAreaWidgetContents_service_2)
        self.gridLayout_4.addWidget(self.scrollArea_service_2, 0, 0, 1, 1)
        self.tabWidget_service.addTab(self.widget_Multicast, "")
        self.verticalLayout_7.addWidget(self.tabWidget_service)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setMidLineWidth(0)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1112, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.menu.addAction(self.actionhelp)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_service.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "OLT厂家"))
        self.comboBox_OLTFactory.setItemText(1, _translate("MainWindow", "FiberHome"))
        self.comboBox_OLTFactory.setItemText(2, _translate("MainWindow", "HuaWei"))
        self.comboBox_OLTFactory.setItemText(3, _translate("MainWindow", "ZTE"))
        self.comboBox_OLTFactory.setItemText(4, _translate("MainWindow", "Bell"))
        self.comboBox_OLTFactory.setItemText(5, _translate("MainWindow", "RHEL"))
        self.label_3.setText(_translate("MainWindow", "IP ADD "))
        self.label_8.setText(_translate("MainWindow", "用户名"))
        self.label_2.setText(_translate("MainWindow", "OLT类型"))
        self.comboBox_OLTType.setItemText(0, _translate("MainWindow", "GPON"))
        self.comboBox_OLTType.setItemText(1, _translate("MainWindow", "EPON"))
        self.label_4.setText(_translate("MainWindow", "登录方式"))
        self.comboBox_loginMethod.setItemText(0, _translate("MainWindow", "Telnet"))
        self.comboBox_loginMethod.setItemText(1, _translate("MainWindow", "SSH2"))
        self.comboBox_loginMethod.setItemText(2, _translate("MainWindow", "SSH"))
        self.label_9.setText(_translate("MainWindow", "登陆密码"))
        self.label_7.setText(_translate("MainWindow", "产品型号："))
        self.comboBox_onuType.setItemText(0, _translate("MainWindow", "吉视汇通-2ETH"))
        self.label_5.setText(_translate("MainWindow", "查询方式："))
        self.comboBox_check.setItemText(0, _translate("MainWindow", "查询未注册ONU"))
        self.comboBox_check.setItemText(1, _translate("MainWindow", "查询PON口下所有ONU"))
        self.comboBox_check.setItemText(2, _translate("MainWindow", "查询单个ONU"))
        self.label_check.setText(_translate("MainWindow", "MAC或SN："))
        item = self.tableWidget_onu.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SN/MAC"))
        item = self.tableWidget_onu.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Slot/Port"))
        item = self.tableWidget_onu.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ONU ID"))
        item = self.tableWidget_onu.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "State"))
        self.pushButton_login.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton_exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_query.setText(_translate("MainWindow", "查询"))
        self.pushButton_reg.setText(_translate("MainWindow", "注册"))
        self.pushButton_addService.setText(_translate("MainWindow", "添加业务"))
        self.pushButton_unreg.setText(_translate("MainWindow", "去注册"))
        self.tabWidget_service.setToolTip(_translate("MainWindow", "<html><head/><body><p>业务配置</p><p><br/></p></body></html>"))
        self.pushButton_add_1.setText(_translate("MainWindow", "+"))
        self.label_service_1.setText(_translate("MainWindow", "业务类型"))
        self.comboBox_service_1.setItemText(0, _translate("MainWindow", "Internet"))
        self.comboBox_service_1.setItemText(1, _translate("MainWindow", "IPTV"))
        self.comboBox_service_1.setItemText(2, _translate("MainWindow", "VOIP"))
        self.comboBox_service_1.setItemText(3, _translate("MainWindow", "TR069"))
        self.label_servicevlanmode_1.setText(_translate("MainWindow", "业务VLAN模式"))
        self.comboBox_servicevlanmode_1.setItemText(0, _translate("MainWindow", "Statcked"))
        self.comboBox_servicevlanmode_1.setItemText(1, _translate("MainWindow", "Tag"))
        self.comboBox_servicevlanmode_1.setItemText(2, _translate("MainWindow", "Untag"))
        self.label_svlan_1.setText(_translate("MainWindow", "SVLAN"))
        self.lineEdit_svlan_1.setText(_translate("MainWindow", "4096"))
        self.label_cvlan_1.setText(_translate("MainWindow", "CVLAN"))
        self.lineEdit_cvlan_1.setText(_translate("MainWindow", "4096"))
        self.label_uservlanmode_1.setText(_translate("MainWindow", "用户VLAN模式"))
        self.comboBox_uservlanmode_1.setItemText(0, _translate("MainWindow", "Transparent"))
        self.comboBox_uservlanmode_1.setItemText(1, _translate("MainWindow", "Translate"))
        self.comboBox_uservlanmode_1.setItemText(2, _translate("MainWindow", "Default"))
        self.comboBox_uservlanmode_1.setItemText(3, _translate("MainWindow", "Untag"))
        self.label_uservlan_1.setText(_translate("MainWindow", "用户VLAN"))
        self.lineEdit_usevlan_1.setText(_translate("MainWindow", "4096"))
        self.tabWidget_service.setTabText(self.tabWidget_service.indexOf(self.widget_Unicast), _translate("MainWindow", " Unicast Service"))
        self.pushButton_add_2.setText(_translate("MainWindow", "+"))
        self.label_service_2.setText(_translate("MainWindow", "业务类型"))
        self.comboBox_service_2.setItemText(0, _translate("MainWindow", "Internet"))
        self.comboBox_service_2.setItemText(1, _translate("MainWindow", "IPTV"))
        self.comboBox_service_2.setItemText(2, _translate("MainWindow", "VOIP"))
        self.comboBox_service_2.setItemText(3, _translate("MainWindow", "TR069"))
        self.label_servicevlanmode_2.setText(_translate("MainWindow", "业务VLAN模式"))
        self.comboBox_servicevlanmode_2.setItemText(0, _translate("MainWindow", "Statcked"))
        self.comboBox_servicevlanmode_2.setItemText(1, _translate("MainWindow", "Tag"))
        self.comboBox_servicevlanmode_2.setItemText(2, _translate("MainWindow", "Untag"))
        self.label_svlan_2.setText(_translate("MainWindow", "SVLAN"))
        self.lineEdit_svlan_2.setText(_translate("MainWindow", "4096"))
        self.label_cvlan_2.setText(_translate("MainWindow", "CVLAN"))
        self.lineEdit_cvlan_2.setText(_translate("MainWindow", "4096"))
        self.label_uservlanmode_2.setText(_translate("MainWindow", "用户VLAN模式"))
        self.comboBox_uservlanmode_2.setItemText(0, _translate("MainWindow", "Transparent"))
        self.comboBox_uservlanmode_2.setItemText(1, _translate("MainWindow", "Translate"))
        self.comboBox_uservlanmode_2.setItemText(2, _translate("MainWindow", "Default"))
        self.comboBox_uservlanmode_2.setItemText(3, _translate("MainWindow", "Untag"))
        self.label_uservlan_2.setText(_translate("MainWindow", "用户VLAN"))
        self.lineEdit_usevlan_2.setText(_translate("MainWindow", "4096"))
        self.tabWidget_service.setTabText(self.tabWidget_service.indexOf(self.widget_Multicast), _translate("MainWindow", "Multicast Service"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.actionhelp.setText(_translate("MainWindow", "help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

